baseURL = 'https://mhmasum0.github.io/qajune2024/'
languageCode = 'en-us'
title = 'QA June 2024'

theme = 'qajune2024'

[taxonomies]
category = 'categories'
tag = 'tags'

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNumbersInTable = true
    tabWidth = 4
    noHl = true
    style = 'catppuccin-latte'